language: node_js

node_js:
    - 0.12
    - 4
    - 5
    - 6
    - 7
    - iojs

sudo: false

after_success:
    - npm install codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
