// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/337587de8c13868283993bfacdcdd1a0f3291e7f/path-to-regexp/index.d.ts
declare module 'path-to-regexp' {
// Type definitions for path-to-regexp v1.0.3
// Project: https://github.com/pillarjs/path-to-regexp
// Definitions by: xica <https://github.com/xica>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped



function pathToRegexp(path: string, keys?: string[], options?: pathToRegexp.Options): RegExp;

namespace pathToRegexp {

    interface Options {
        sensitive?: boolean;
        strict?: boolean;
        end?: boolean;
    }

}

export = pathToRegexp;
}
